include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
  errors:
    todo: warning
    deprecated_member_use: warning

linter:
  rules:
    - prefer_single_quotes
    - avoid_relative_lib_imports
    - always_declare_return_types
    - directives_ordering
    - sort_constructors_first
    - unnecessary_const
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - camel_case_types
