import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/models/asmaul_husna_model.dart';

final asmaulHusnaProvider = Provider<List<AsmaulHusna>>((ref) {
  return _asmaulHusnaData;
});

final List<AsmaulHusna> _asmaulHusnaData = [
  AsmaulHusna(number: 1, latinName: "Ar Rahman", arabicName: "الرحمن", meaning: "Yang Maha Pengasih", description: "Allah memiliki kasih sayang yang luas bagi seluruh makhluk-Nya."),
  AsmaulHusna(number: 2, latinName: "Ar Rahim", arabicName: "الرحيم", meaning: "Yang Maha Penyayang", description: "Allah memiliki kasih sayang yang khusus bagi orang-orang beriman."),
  AsmaulHusna(number: 3, latinName: "Al Malik", arabicName: "الملك", meaning: "Yang Maha Raja", description: "Allah adalah penguasa mutlak atas seluruh alam semesta."),
  AsmaulHusna(number: 4, latinName: "Al Quddus", arabicName: "القدوس", meaning: "Yang Maha Suci", description: "Allah suci dari segala kekurangan dan cela."),
  AsmaulHusna(number: 5, latinName: "As Salam", arabicName: "السلام", meaning: "Yang Maha Memberi Kesejahteraan", description: "Allah adalah sumber kedamaian dan keselamatan."),
  AsmaulHusna(number: 6, latinName: "Al Mu'min", arabicName: "المؤمن", meaning: "Yang Maha Memberi Keamanan", description: "Allah memberikan rasa aman kepada hamba-hamba-Nya."),
  AsmaulHusna(number: 7, latinName: "Al Muhaimin", arabicName: "المهيمن", meaning: "Yang Maha Memelihara", description: "Allah memelihara dan mengawasi segala sesuatu."),
  AsmaulHusna(number: 8, latinName: "Al Aziz", arabicName: "العزيز", meaning: "Yang Maha Perkasa", description: "Allah memiliki kekuatan yang mengalahkan segalanya."),
  AsmaulHusna(number: 9, latinName: "Al Jabbar", arabicName: "الجبار", meaning: "Yang Maha Berkuasa", description: "Allah memiliki kehendak yang harus dipenuhi oleh makhluk-Nya."),
  AsmaulHusna(number: 10, latinName: "Al Mutakabbir", arabicName: "المتكبر", meaning: "Yang Maha Megah", description: "Allah memiliki kebesaran dan kemuliaan yang tiada tara."),
  AsmaulHusna(number: 11, latinName: "Al Khaliq", arabicName: "الخالق", meaning: "Yang Maha Pencipta", description: "Allah menciptakan segala sesuatu dari ketiadaan."),
  AsmaulHusna(number: 12, latinName: "Al Baari'", arabicName: "البارئ", meaning: "Yang Maha Melepaskan", description: "Allah membentuk dan merencanakan penciptaan dengan sempurna."),
  AsmaulHusna(number: 13, latinName: "Al Mushawwir", arabicName: "المصور", meaning: "Yang Maha Membentuk Rupa", description: "Allah memberikan bentuk dan rupa yang berbeda-beda pada makhluk-Nya."),
  AsmaulHusna(number: 14, latinName: "Al Ghaffar", arabicName: "الغفار", meaning: "Yang Maha Pengampun", description: "Allah berulang kali mengampuni dosa-dosa hamba-Nya."),
  AsmaulHusna(number: 15, latinName: "Al Qahhar", arabicName: "القهار", meaning: "Yang Maha Menundukkan", description: "Allah menundukkan segala sesuatu di bawah kekuasaan-Nya."),
  AsmaulHusna(number: 16, latinName: "Al Wahhab", arabicName: "الوهاب", meaning: "Yang Maha Pemberi Karunia", description: "Allah memberi tanpa mengharap imbalan."),
  AsmaulHusna(number: 17, latinName: "Ar Razzaq", arabicName: "الرزاق", meaning: "Yang Maha Pemberi Rezeki", description: "Allah menjamin rezeki bagi seluruh makhluk-Nya."),
  AsmaulHusna(number: 18, latinName: "Al Fattah", arabicName: "الفتاح", meaning: "Yang Maha Pembuka Rahmat", description: "Allah membuka pintu-pintu rahmat dan solusi."),
  AsmaulHusna(number: 19, latinName: "Al 'Alim", arabicName: "العليم", meaning: "Yang Maha Mengetahui", description: "Ilmu Allah meliputi segala sesuatu yang nyata maupun gaib."),
  AsmaulHusna(number: 20, latinName: "Al Qabidh", arabicName: "القابض", meaning: "Yang Maha Menyempitkan", description: "Allah menyempitkan rezeki atau perasaan sesuai hikmah-Nya."),
  AsmaulHusna(number: 21, latinName: "Al Baasith", arabicName: "الباسط", meaning: "Yang Maha Melapangkan", description: "Allah melapangkan rezeki atau perasaan sesuai rahmat-Nya."),
  AsmaulHusna(number: 22, latinName: "Al Khaafidh", arabicName: "الخافض", meaning: "Yang Maha Merendahkan", description: "Allah merendahkan derajat orang yang sombong."),
  AsmaulHusna(number: 23, latinName: "Ar Raafi'", arabicName: "الرافع", meaning: "Yang Maha Meninggikan", description: "Allah meninggikan derajat orang-orang beriman."),
  AsmaulHusna(number: 24, latinName: "Al Mu'izz", arabicName: "المعز", meaning: "Yang Maha Memuliakan", description: "Allah memberikan kemuliaan kepada siapa yang Dia kehendaki."),
  AsmaulHusna(number: 25, latinName: "Al Mudzil", arabicName: "المذل", meaning: "Yang Maha Menghinakan", description: "Allah menghinakan siapa pun yang Dia kehendaki."),
  AsmaulHusna(number: 26, latinName: "As Samii'", arabicName: "السميع", meaning: "Yang Maha Mendengar", description: "Pendengaran Allah tidak terbatas oleh suara atau bahasa."),
  AsmaulHusna(number: 27, latinName: "Al Bashiir", arabicName: "البصير", meaning: "Yang Maha Melihat", description: "Penglihatan Allah meliputi segala sesuatu yang paling halus sekalipun."),
  AsmaulHusna(number: 28, latinName: "Al Hakam", arabicName: "الحكم", meaning: "Yang Maha Menetapkan", description: "Allah adalah hakim yang paling adil dalam menetapkan hukum."),
  AsmaulHusna(number: 29, latinName: "Al 'Adl", arabicName: "العدل", meaning: "Yang Maha Adil", description: "Keadilan Allah bersifat mutlak dan sempurna."),
  AsmaulHusna(number: 30, latinName: "Al Lathiif", arabicName: "اللطيف", meaning: "Yang Maha Lembut", description: "Allah Maha Lembut dalam perbuatan-Nya dan Maha Mengetahui hal-hal halus."),
  AsmaulHusna(number: 31, latinName: "Al Khabiir", arabicName: "الخبير", meaning: "Yang Maha Mengenal", description: "Allah mengetahui rahasia-rahasia terdalam segala sesuatu."),
  AsmaulHusna(number: 32, latinName: "Al Haliim", arabicName: "الحليم", meaning: "Yang Maha Penyantun", description: "Allah tidak terburu-buru memberikan hukuman kepada pendosa."),
  AsmaulHusna(number: 33, latinName: "Al 'Azhiim", arabicName: "العظيم", meaning: "Yang Maha Agung", description: "Keagungan Allah melampaui segala nalar manusia."),
  AsmaulHusna(number: 34, latinName: "Al Ghafuur", arabicName: "الغفور", meaning: "Yang Maha Pengampun", description: "Allah memberikan ampunan yang sempurna kepada hamba-Nya."),
  AsmaulHusna(number: 35, latinName: "As Syakuur", arabicName: "الشكور", meaning: "Yang Maha Pembalas Budi", description: "Allah melipatgandakan pahala atas amal kebaikan sekecil apa pun."),
  AsmaulHusna(number: 36, latinName: "Al 'Aliy", arabicName: "العلى", meaning: "Yang Maha Tinggi", description: "Allah memiliki derajat dan kedudukan tertinggi."),
  AsmaulHusna(number: 37, latinName: "Al Kabiir", arabicName: "الكبير", meaning: "Yang Maha Besar", description: "Kebesaran Allah tidak bisa dibayangkan oleh ciptaan-Nya."),
  AsmaulHusna(number: 38, latinName: "Al Hafizh", arabicName: "الحفيظ", meaning: "Yang Maha Memelihara", description: "Allah menjaga segala sesuatu agar tidak hancur atau hilang."),
  AsmaulHusna(number: 39, latinName: "Al Muqiit", arabicName: "المقيت", meaning: "Yang Maha Pemberi Kecukupan", description: "Allah memberikan rezeki dan kekuatan kepada semua makhluk-Nya."),
  AsmaulHusna(number: 40, latinName: "Al Hasiib", arabicName: "الحسيب", meaning: "Yang Maha Membuat Perhitungan", description: "Allah mencatat dan menghitung segala amal perbuatan dengan akurat."),
  AsmaulHusna(number: 41, latinName: "Al Jaliil", arabicName: "الجليل", meaning: "Yang Maha Luhur", description: "Allah memiliki kemuliaan yang tidak dapat ditandingi."),
  AsmaulHusna(number: 42, latinName: "Al Kariim", arabicName: "الكريم", meaning: "Yang Maha Pemurah", description: "Kebaikan dan pemberian Allah selalu melimpah ruah."),
  AsmaulHusna(number: 43, latinName: "Ar Raqiib", arabicName: "الرقيب", meaning: "Yang Maha Mengawasi", description: "Allah selalu mengawasi setiap perbuatan hamba-Nya."),
  AsmaulHusna(number: 44, latinName: "Al Mujiib", arabicName: "المجيب", meaning: "Yang Maha Mengabulkan", description: "Allah mengabulkan doa dan permohonan hamba-Nya."),
  AsmaulHusna(number: 45, latinName: "Al Waasi'", arabicName: "الواسع", meaning: "Yang Maha Luas", description: "Karunia, rahmat, dan ilmu Allah meliputi segalanya."),
  AsmaulHusna(number: 46, latinName: "Al Hakiim", arabicName: "الحكيم", meaning: "Yang Maha Bijaksana", description: "Setiap keputusan dan ketetapan Allah memiliki hikmah yang dalam."),
  AsmaulHusna(number: 47, latinName: "Al Waduud", arabicName: "الودود", meaning: "Yang Maha Mengasihi", description: "Allah sangat mencintai hamba-hamba-Nya yang taat."),
  AsmaulHusna(number: 48, latinName: "Al Majiid", arabicName: "المجيد", meaning: "Yang Maha Mulia", description: "Kemuliaan Allah bersifat mutlak dan abadi."),
  AsmaulHusna(number: 49, latinName: "Al Baa'its", arabicName: "الباعث", meaning: "Yang Maha Membangkitkan", description: "Allah membangkitkan manusia dari kubur pada Hari Kiamat."),
  AsmaulHusna(number: 50, latinName: "As Syahiid", arabicName: "الشهيد", meaning: "Yang Maha Menyaksikan", description: "Tidak ada yang terluput dari persaksian Allah."),
  AsmaulHusna(number: 51, latinName: "Al Haqq", arabicName: "الحق", meaning: "Yang Maha Benar", description: "Kebenaran Allah adalah pasti dan tak terbantahkan."),
  AsmaulHusna(number: 52, latinName: "Al Wakiil", arabicName: "الوكيل", meaning: "Yang Maha Memelihara", description: "Allah adalah sebaik-baik penolong dan tempat bersandar."),
  AsmaulHusna(number: 53, latinName: "Al Qawiyyu", arabicName: "القوى", meaning: "Yang Maha Kuat", description: "Kekuatan Allah tidak dapat dikalahkan oleh siapa pun."),
  AsmaulHusna(number: 54, latinName: "Al Matiin", arabicName: "المتين", meaning: "Yang Maha Kokoh", description: "Ketetapan dan kekuasaan Allah sangat kokoh."),
  AsmaulHusna(number: 55, latinName: "Al Waliyy", arabicName: "الولى", meaning: "Yang Maha Melindungi", description: "Allah memberikan perlindungan kepada hamba-hamba-Nya yang beriman."),
  AsmaulHusna(number: 56, latinName: "Al Hamiid", arabicName: "الحميد", meaning: "Yang Maha Terpuji", description: "Hanya Allah yang paling berhak mendapat segala pujian."),
  AsmaulHusna(number: 57, latinName: "Al Muhshii", arabicName: "المحصى", meaning: "Yang Maha Menghitung", description: "Ilmu Allah mencakup perhitungan yang sangat detail atas segala sesuatu."),
  AsmaulHusna(number: 58, latinName: "Al Mubdi'", arabicName: "المبدئ", meaning: "Yang Maha Memulai", description: "Allah memulai penciptaan dari ketiadaan."),
  AsmaulHusna(number: 59, latinName: "Al Mu'iid", arabicName: "المعيد", meaning: "Yang Maha Mengembalikan Kehidupan", description: "Allah akan mengembalikan kehidupan kepada yang mati."),
  AsmaulHusna(number: 60, latinName: "Al Muhyii", arabicName: "المحيى", meaning: "Yang Maha Menghidupkan", description: "Hanya Allah yang bisa memberi kehidupan."),
  AsmaulHusna(number: 61, latinName: "Al Mumiitu", arabicName: "المميت", meaning: "Yang Maha Mematikan", description: "Allah memiliki kekuasaan penuh untuk mencabut nyawa makhluk."),
  AsmaulHusna(number: 62, latinName: "Al Hayyu", arabicName: "الحي", meaning: "Yang Maha Hidup", description: "Kehidupan Allah kekal abadi tanpa awal maupun akhir."),
  AsmaulHusna(number: 63, latinName: "Al Qayyuum", arabicName: "القيوم", meaning: "Yang Maha Mandiri", description: "Allah berdiri sendiri dan mengurus seluruh ciptaan-Nya."),
  AsmaulHusna(number: 64, latinName: "Al Waajid", arabicName: "الواجد", meaning: "Yang Maha Penemu", description: "Allah tidak membutuhkan siapa pun dan Maha Memiliki segalanya."),
  AsmaulHusna(number: 65, latinName: "Al Maajid", arabicName: "الماجد", meaning: "Yang Maha Mulia", description: "Allah memiliki kesempurnaan kemuliaan."),
  AsmaulHusna(number: 66, latinName: "Al Wahid", arabicName: "الواحد", meaning: "Yang Maha Esa", description: "Allah Maha Esa, tiada sekutu bagi-Nya."),
  AsmaulHusna(number: 67, latinName: "Al Ahad", arabicName: "الأحد", meaning: "Yang Maha Tunggal", description: "Allah adalah satu-satunya yang patut disembah."),
  AsmaulHusna(number: 68, latinName: "As Samad", arabicName: "الصمد", meaning: "Yang Maha Dibutuhkan", description: "Allah adalah tempat bergantung semua makhluk."),
  AsmaulHusna(number: 69, latinName: "Al Qaadir", arabicName: "القادر", meaning: "Yang Maha Menentukan", description: "Allah mampu melakukan segala sesuatu."),
  AsmaulHusna(number: 70, latinName: "Al Muqtadir", arabicName: "المقتدر", meaning: "Yang Maha Berkuasa", description: "Kekuasaan Allah tidak terbatas oleh apa pun."),
  AsmaulHusna(number: 71, latinName: "Al Muqaddim", arabicName: "المقدم", meaning: "Yang Maha Mendahulukan", description: "Allah mendahulukan sebagian makhluk atas yang lain."),
  AsmaulHusna(number: 72, latinName: "Al Mu'akkhir", arabicName: "المؤخر", meaning: "Yang Maha Mengakhirkan", description: "Allah mengakhirkan sesuatu sesuai kehendak-Nya."),
  AsmaulHusna(number: 73, latinName: "Al Awwal", arabicName: "الأول", meaning: "Yang Maha Awal", description: "Allah ada sebelum segala sesuatu."),
  AsmaulHusna(number: 74, latinName: "Al Aakhir", arabicName: "الآخر", meaning: "Yang Maha Akhir", description: "Allah tetap ada setelah segala sesuatu binasa."),
  AsmaulHusna(number: 75, latinName: "Az Zhaahir", arabicName: "الظاهر", meaning: "Yang Maha Nyata", description: "Keberadaan Allah sangat jelas dan nyata."),
  AsmaulHusna(number: 76, latinName: "Al Baathin", arabicName: "الباطن", meaning: "Yang Maha Gaib", description: "Allah tidak dapat dilihat oleh mata manusia di dunia."),
  AsmaulHusna(number: 77, latinName: "Al Waali", arabicName: "الوالي", meaning: "Yang Maha Memerintah", description: "Allah mengatur dan mengurus seluruh alam."),
  AsmaulHusna(number: 78, latinName: "Al Muta'ali", arabicName: "المتعالي", meaning: "Yang Maha Tinggi", description: "Allah Maha Suci dari sifat-sifat makhluk."),
  AsmaulHusna(number: 79, latinName: "Al Barru", arabicName: "البر", meaning: "Yang Maha Pelimpah Kebaikan", description: "Kebaikan Allah sangat melimpah kepada hamba-Nya."),
  AsmaulHusna(number: 80, latinName: "At Tawwaab", arabicName: "التواب", meaning: "Yang Maha Penerima Tobat", description: "Allah selalu menerima tobat hamba-Nya."),
  AsmaulHusna(number: 81, latinName: "Al Muntaqim", arabicName: "المنتقم", meaning: "Yang Maha Pemberi Balasan", description: "Allah memberikan balasan yang setimpal atas perbuatan."),
  AsmaulHusna(number: 82, latinName: "Al 'Afuww", arabicName: "العفو", meaning: "Yang Maha Pemaaf", description: "Allah menghapus dosa-dosa hamba-Nya."),
  AsmaulHusna(number: 83, latinName: "Ar Ra'uuf", arabicName: "الرؤوف", meaning: "Yang Maha Pengasih", description: "Kasih sayang Allah sangat besar dan mendalam."),
  AsmaulHusna(number: 84, latinName: "Maalikul Mulki", arabicName: "مالك الملك", meaning: "Yang Maha Penguasa Kerajaan", description: "Allah memiliki seluruh kerajaan dan kekuasaan."),
  AsmaulHusna(number: 85, latinName: "Dzul Jalaali Wal Ikraam", arabicName: "ذو الجلال والإكرام", meaning: "Yang Maha Memiliki Kebesaran dan Kemuliaan", description: "Allah memiliki keagungan dan kemuliaan yang tak terhingga."),
  AsmaulHusna(number: 86, latinName: "Al Muqsith", arabicName: "المقسط", meaning: "Yang Maha Pemberi Keadilan", description: "Allah memberikan keadilan kepada semua makhluk-Nya."),
  AsmaulHusna(number: 87, latinName: "Al Jamii'", arabicName: "الجامع", meaning: "Yang Maha Mengumpulkan", description: "Allah mengumpulkan seluruh makhluk pada Hari Kiamat."),
  AsmaulHusna(number: 88, latinName: "Al Ghaniyy", arabicName: "الغنى", meaning: "Yang Maha Kaya", description: "Kekayaan Allah tidak ada batasnya."),
  AsmaulHusna(number: 89, latinName: "Al Mughnii", arabicName: "المغنى", meaning: "Yang Maha Pemberi Kekayaan", description: "Allah memberikan kekayaan kepada siapa yang Dia kehendaki."),
  AsmaulHusna(number: 90, latinName: "Al Maani'", arabicName: "المانع", meaning: "Yang Maha Mencegah", description: "Allah mencegah sesuatu terjadi jika Dia tidak menghendaki."),
  AsmaulHusna(number: 91, latinName: "Ad Dhaarr", arabicName: "الضار", meaning: "Yang Maha Pemberi Bahaya", description: "Allah bisa memberikan bahaya jika ada hikmah di baliknya."),
  AsmaulHusna(number: 92, latinName: "An Naafi'", arabicName: "النافع", meaning: "Yang Maha Pemberi Manfaat", description: "Allah memberikan manfaat kepada siapa yang Dia kehendaki."),
  AsmaulHusna(number: 93, latinName: "An Nuur", arabicName: "النور", meaning: "Yang Maha Bercahaya", description: "Allah adalah cahaya yang menerangi alam semesta."),
  AsmaulHusna(number: 94, latinName: "Al Haadi", arabicName: "الهادئ", meaning: "Yang Maha Pemberi Petunjuk", description: "Allah memberikan petunjuk kepada siapa yang Dia kehendaki."),
  AsmaulHusna(number: 95, latinName: "Al Badii'", arabicName: "البديع", meaning: "Yang Maha Pencipta Tiada Banding", description: "Allah menciptakan segala sesuatu dengan sangat indah."),
  AsmaulHusna(number: 96, latinName: "Al Baaqii", arabicName: "الباقي", meaning: "Yang Maha Kekal", description: "Keberadaan Allah abadi dan tidak akan musnah."),
  AsmaulHusna(number: 97, latinName: "Al Waarits", arabicName: "الوارث", meaning: "Yang Maha Pewaris", description: "Allah adalah pewaris seluruh alam setelah makhluk-Nya binasa."),
  AsmaulHusna(number: 98, latinName: "Ar Rasyiid", arabicName: "الرشيد", meaning: "Yang Maha Pandai", description: "Allah adalah sumber segala kebijaksanaan dan petunjuk."),
  AsmaulHusna(number: 99, latinName: "As Shabuur", arabicName: "الصبور", meaning: "Yang Maha Sabar", description: "Allah tidak tergesa-gesa dalam menghukum dan memberikan rahmat."),
];
